language: node_js
node_js:
- lts/*
- node
before_install:
- npm install -g npm@latest greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
env:
  global:
    secure: DCF3EXoGTCks4oHodynbA7PkGBuC5/bidLb7GQJ/tMlHAneD+OWFLiEGzdd00wAvNeOtcBt9XI27BFw1NkVN1vqi8FW9u+4xX9LdfKTOEZ5KfE5hLwfkoyA/DWpUbuzH4w3J6ICMaCJb/TM1VO0PGav0GvviWmdcw+D22cKFOY5sWs7GRmfRoxB9hQboWdAwKGvO8g5N55M2hr9qEASlun6oNCxQs7I6oftrwgLywo26558R6VXiIxYPukPC2Xb7SAUKp2AalR/htojKoN2S5HER7r+G6xitQrqasaXC7IXAoW4NSM/JVHNFqytEiX/wcMBf+nNe5UuOeO90SCdc2kOFUOSkL8NJ7+PkIF3Fp6B/23YF1VT9SBBZxsC9l4oR8+xz6igq0TQyN6dH0dZzqrGg0rbwYV7/476eX3F57vVSFV8yAvUQ7fT7dg2lv+uN5l9F4KwO3nSzVNtXG4lMWGrizukCtTEjuFnlJWnbjKSSehfycn/ezmVd1EeaRrWy/zpa+V/i6nTHUSWI5MkoADveRoKZkRCM8tVtLn7NODkKHhDTDKveNqenz4eBlZXOloeS5xTJH3/PHHxKhuomojMhxyIta5BcLxLbvkmfmS7dXyzmgSNMl4XO1zl4NXNcKX5C2LGLcxynIk0UbZTVKWqDNfHHN56bF9hFlTZ3nzM=
